# Configs for pwills.com

title: "pwills.com"
name: "pwills.com"
email: peter@pwills.com
url: "http://www.pwills.com"
repository: "peterewills/peterewills.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Thanmai Ravoori"
  avatar : "https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia.licdn.com%2Fdms%2Fimage%2FC5603AQGmiCq4gsHDvg%2Fprofile-displayphoto-shrink_800_800%2F0%2F1628230210321%3Fe%3D2147483647%26v%3Dbeta%26t%3DM1YJm3m-xiawErcY__vnSmGxqDIvbUFJmSr6HYRK4vo&tbnid=NTAoRIdkaHrzaM&vet=12ahUKEwia4ZKH2Y-CAxWV8ckDHRGRAaIQMygAegQIARBA..i&imgrefurl=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fthanmai-ravoori&docid=nTFyPSEZrcNi1M&w=800&h=800&q=thanmai%20ravoori&ved=2ahUKEwia4ZKH2Y-CAxWV8ckDHRGRAaIQMygAegQIARBA"
  bio    : "I enjoy learning new technologies and interested in getting updated with the technology."
  location: "Dekalb, IL"
  github : ThanmaiRavoori
  linkedin: thanmai-ravoori
  email  : travoori@gmail.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
