# Configs for pwills.com

title: "Thanmai.com"
name: "Thanmai.com"
email: travoori@gmail.com
url: "http://www.pwills.com"
repository: "thanmairavoori/thanmairavoori.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# settings for author profile
author:
  name   : "Thanmai Ravoori"
  avatar : "https://media.licdn.com/dms/image/D5603AQGz9cg8iWmLdg/profile-displayphoto-shrink_800_800/0/1697582035786?e=1703721600&v=beta&t=w8VxUiK0RnT8ZD6VsgBAxu2a403xotkkhza30HjinBs"
  bio    : "I enjoy learning new technologies and interested in getting updated with the technology."
  location: "Dekalb, IL"
  github : ThanmaiRavoori
  linkedin: thanmai-ravoori
  email  : travoori@gmail.com


# # comments by disqus
comments:
  provider: "disqus"
  disqus:
    shortname: "pwills-com"

analytics:
  provider: "google"
  google:
    tracking_id: "UA-116208936-1"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
